/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "gui\gui_thread.h"
#include "GUI.h"


//图标的文本位于图标下方。
/*********************************************************************
*
*       user config
*
**********************************************************************
*/
//主页定义
#define x_size 320                //主页区域x
#define y_size 240                //主页区域y
#define MIAN_PAGE_REFRESH_RATE 1000 //主页更新率

#define MAIN_PAGE_NUM     2       //主页的数量
#define ICON_NUM_X        4       //每行图标个数
#define ICON_NUM_Y        3       //每列图标个数
#define ICON_X_INTERVAL   25      //每行图标间隔
#define ICON_Y_INTERVAL   20      //每列图标间隔

#define ICON_NUM          (ICON_NUM_X*ICON_NUM_y)   //单页支持的最大图标数量
#define ICON_EDGE_SIZE    3       //图标被选中后的边框距离，单位像素
#define TEXT_EDGE_SIZE    5       //文本和位图间距，单位像素
#define TEXT_FONT         GUI_FONT_6X8  //使用字体

#define ARRAY(X)    (sizeof(X)/sizeof(X[0]))
/*********************************************************************
*
*       variables
*
**********************************************************************
*/
extern GUI_CONST_STORAGE GUI_BITMAP bmiconview_message;
extern GUI_CONST_STORAGE GUI_BITMAP bmiconview_phone;
extern GUI_CONST_STORAGE GUI_BITMAP bmiconview_photo;
extern GUI_CONST_STORAGE GUI_BITMAP bmicon_smile;

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0        (GUI_ID_USER + 0x00)
#define ID_ICONVIEW_0        (GUI_ID_USER + 0x01)

// USER START (Optionally insert additional defines)
// USER END
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/


//_icon图标对象表示的是包含位图和文本的所有区域
struct _icon {
  //变量
  unsigned short icon_x;            //图标左上角点x坐标
  unsigned short icon_y;            //图标左上角点y坐标
  unsigned short icon_xsize;        //图标x尺寸
  unsigned short icon_ysize;        //图标y尺寸
  unsigned short text_y;            //文本区域左上角点y坐标
  unsigned short bitmap_xsize;      //位图区域x尺寸，起点和图标一致
  unsigned short bitmap_ysize;      //位图区域y尺寸
  //赋初值
  const char       * pText;         //图标名称
  const GUI_BITMAP * pBitmap;       //图标位图
};
typedef struct _icon _ICON;
typedef struct _icon* _ICON_T;

struct _page {
//  unsigned char icon_num_x;         //每行图标个数
//  unsigned char icon_num_y;         //每列图标个数
//  unsigned char icon_edge_size;     //图标被选中后的边框距离，单位像素
//  unsigned char text_edge_size;     //字体图标间距，单位像素
//  unsigned short icon_x_interval;   //每行图标间隔
//  unsigned short icon_y_interval;   //每列图标间隔
  unsigned char icon_num;           //图标数量
  _ICON_T icon_list;                 //图标集
  GUI_FONT * pFont;
};
typedef struct _page _PAGE;
typedef struct _page* _PAGE_T;

//主页1图标列表
static _ICON icon_list1[]={
  {.pText="phone",.pBitmap=&bmiconview_phone},
  {.pText="message",.pBitmap=&bmiconview_message},
  {.pText="photo",.pBitmap=&bmiconview_photo},
  {.pText="phone",.pBitmap=&bmiconview_phone},
  {.pText="message",.pBitmap=&bmiconview_message},
  {.pText="photo",.pBitmap=&bmiconview_photo},
};
//主页2图标列表
static _ICON icon_list2[]={
  {.pText="photo",.pBitmap=&bmiconview_photo},
  {.pText="message",.pBitmap=&bmiconview_message},
  {.pText="phone",.pBitmap=&bmiconview_phone},
  {.pText="photo",.pBitmap=&bmiconview_photo},
  {.pText="message",.pBitmap=&bmiconview_message},
  {.pText="phone",.pBitmap=&bmiconview_phone},
  {.pText="message",.pBitmap=&bmiconview_message},
  {.pText="phone",.pBitmap=&bmiconview_phone},
};

//static _ICON icon_list[MAIN_PAGE_NUM][ICON_NUM]={
//  //主页1图标列表
//  {
//      {.pText="phone",.pBitmap=&bmiconview_phone},
//      {.pText="message",.pBitmap=&bmiconview_message},
//      {.pText="photo",.pBitmap=&bmiconview_photo},
//      {.pText="phone",.pBitmap=&bmiconview_phone},
//      {.pText="message",.pBitmap=&bmiconview_message},
//      {.pText="photo",.pBitmap=&bmiconview_photo},
//  }
//,
//  //主页2图标列表
//  {
//      {.pText="photo",.pBitmap=&bmiconview_photo},
//      {.pText="message",.pBitmap=&bmiconview_message},
//      {.pText="phone",.pBitmap=&bmiconview_phone},
//      {.pText="photo",.pBitmap=&bmiconview_photo},
//      {.pText="message",.pBitmap=&bmiconview_message},
//      {.pText="phone",.pBitmap=&bmiconview_phone},
//      {.pText="message",.pBitmap=&bmiconview_message},
//      {.pText="phone",.pBitmap=&bmiconview_phone},
//  }
//};

static _PAGE _main_page[MAIN_PAGE_NUM]={
{.icon_num=ARRAY(icon_list1),.icon_list=icon_list1,.pFont=TEXT_FONT},
{.icon_num=ARRAY(icon_list2),.icon_list=icon_list2,.pFont=TEXT_FONT},
};

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "win_mainpage", ID_WINDOW_0, 0, 0, x_size, y_size, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

static void _cbDialog(WM_MESSAGE * pMsg) {

//  WM_HWIN hItem;
  unsigned char i;
  unsigned char t;
  unsigned char line_num;
  unsigned char column_num;

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG: 
    //初始化页参数
    for(i=0;i<MAIN_PAGE_NUM;i++){                   //页号
      for(t=0;t<_main_page[i].icon_num;t++) {       //图标号
        _main_page[i].icon_list[t].icon_xsize=(LCD_xsize-(ICON_NUM_X+1)*ICON_X_INTERVAL)/ICON_NUM_X;
        _main_page[i].icon_list[t].icon_ysize=(LCD_ysize-(ICON_NUM_Y+1)*ICON_Y_INTERVAL)/ICON_NUM_Y;
        line_num=t%ICON_NUM_X;                  //所在行
        column_num=t/ICON_NUM_X;                //所在列
        _main_page[i].icon_list[t].icon_x=(line_num+1)*ICON_X_INTERVAL+line_num*_main_page[i].icon_list[t].icon_xsize;
        _main_page[i].icon_list[t].icon_y=(column_num+1)*ICON_Y_INTERVAL+column_num*_main_page[i].icon_list[t].icon_ysize;
        _main_page[i].icon_list[t].text_y=_main_page[i].icon_list[t].icon_y+
            _main_page[i].icon_list[t].icon_ysize-
            _main_page[i].pFont->YSize-TEXT_EDGE_SIZE;
        _main_page[i].icon_list[t].bitmap_xsize=_main_page[i].icon_list[t].icon_xsize;
        _main_page[i].icon_list[t].bitmap_ysize=_main_page[i].icon_list[t].text_y-_main_page[i].icon_list[t].icon_y;
      }
    }
    break;
    
  case WM_PAINT:
    //绘制背景
    GUI_SetBkColor(0x00FFC880);         //自定义调色
    GUI_Clear();
    GUI_DrawBitmapEx(&bmicon_smile, LCD_GetXSize()/2,
    (LCD_GetYSize()-100)/2,bmicon_smile.XSize/2,(bmicon_smile.YSize-100)/2,1000,1000);  //bmicon_smile.XSize/2λͼ��λ��ΪͼƬ�е�  LCD_GetXSize()/2 ��λ��λ��Ļ�е�  1000Ϊԭʼ�ߴ�

    //绘制图标
    GUI_SetColor(GUI_BLACK);
    for(i=0;i<MAIN_PAGE_NUM;i++){                   //页号
      for(t=0;t<_main_page[i].icon_num;t++) {       //图标号
        //绘制图标区域
        GUI_DrawRect(_main_page[i].icon_list[t].icon_x, _main_page[i].icon_list[t].icon_y,
            _main_page[i].icon_list[t].icon_x+_main_page[i].icon_list[t].icon_xsize,
            _main_page[i].icon_list[t].icon_y+_main_page[i].icon_list[t].icon_ysize);
        //绘制字体区域
        GUI_SetColor(GUI_ORANGE);

      }
    }


    break;
    
  case WM_TIMER:
    WM_RestartTimer(pMsg->Data.v, MIAN_PAGE_REFRESH_RATE);
    WM_InvalidateWindow(pMsg->hWin);

//    GUI_PID_STATE State;
//    GUI_PID_GetState(&State);
//    rt_kprintf("%d %d %d\r\n",State.Pressed,State.x,State.y);
    break;
  
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createwin_mainpage
*/
WM_HWIN Createwin_mainpage(void);
WM_HWIN Createwin_mainpage(void) {
  WM_HWIN hWin;
//  WM_CF_MEMDEV
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog,WM_CF_SHOW , 0, 0);
  switch_win(hWin,MIAN_PAGE_WIN_ID);

//  WM_DisableMemdev(hWin);
//  WM_EnableMemdev(hWin);
  WM_CreateTimer(hWin, 0, MIAN_PAGE_REFRESH_RATE, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
